/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    cases: Case;
    testimonials: Testimonial;
    media: Media;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'he') | ('en' | 'ru' | 'he')[];
  globals: {
    home: Home;
    showreel: Showreel;
    'services-index': ServicesIndex;
    'portfolio-page': PortfolioPage;
    'testimonials-page': TestimonialsPage;
    about: About;
    nav: Nav;
    'lead-form': LeadForm;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    showreel: ShowreelSelect<false> | ShowreelSelect<true>;
    'services-index': ServicesIndexSelect<false> | ServicesIndexSelect<true>;
    'portfolio-page': PortfolioPageSelect<false> | PortfolioPageSelect<true>;
    'testimonials-page': TestimonialsPageSelect<false> | TestimonialsPageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    nav: NavSelect<false> | NavSelect<true>;
    'lead-form': LeadFormSelect<false> | LeadFormSelect<true>;
  };
  locale: 'en' | 'ru' | 'he';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Страницы услуг. Порядок задаётся полем «Порядок».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Адрес страницы: /services/<slug>. Менять только вместе с редиректом.
   */
  slug: string;
  order: number;
  /**
   * Большое изображение справа в шапке страницы. Если пусто — шапка рисуется без фото.
   */
  hero?: (number | null) | Media;
  /**
   * Бейдж в шапке страницы и в списке услуг.
   */
  label?: string | null;
  h1?: string | null;
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: string | null;
  /**
   * Каждый блок — секция страницы: заголовок, вступление и список. Включите «Нумерованный», чтобы список стал таймлайном с номерами.
   */
  blocks?:
    | {
        heading: string;
        intro?: string | null;
        ordered?: boolean | null;
        list?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  index?: {
    title?: string | null;
    teaser?: string | null;
  };
  /**
   * Заголовок и описание страницы для поиска и соцсетей.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Описание для SEO и скринридеров. Оставьте пустым для декоративных изображений.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Кейсы портфолио. Категория («Тег») должна совпадать с фильтром на странице портфолио.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  /**
   * Адрес: /portfolio/<slug>
   */
  slug: string;
  order: number;
  /**
   * Показывается в сетке портфолио и на странице кейса (16:9).
   */
  cover?: (number | null) | Media;
  title?: string | null;
  /**
   * Должен совпадать с одной из категорий фильтра.
   */
  tag?: string | null;
  client?: string | null;
  result?: string | null;
  summary?: string | null;
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  order: number;
  quote?: string | null;
  name?: string | null;
  company?: string | null;
  role?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Заявки с сайта. Дублируются в CRM через вебхук — здесь хранится их копия.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  status?: ('new' | 'in_progress' | 'won' | 'lost') | null;
  service?: string | null;
  budget?: string | null;
  business?: string | null;
  message?: string | null;
  note?: string | null;
  page?: string | null;
  locale?: string | null;
  whatsappOptIn?: boolean | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Ключ дедупликации — совпадает с событием Meta CAPI.
   */
  eventId?: string | null;
  crmForwarded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Администратор управляет пользователями и настройками.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  hero?: T;
  label?: T;
  h1?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?: T;
  blocks?:
    | T
    | {
        heading?: T;
        intro?: T;
        ordered?: T;
        list?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  index?:
    | T
    | {
        title?: T;
        teaser?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  cover?: T;
  title?: T;
  tag?: T;
  client?: T;
  result?: T;
  summary?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  services?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  order?: T;
  quote?: T;
  name?: T;
  company?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  status?: T;
  service?: T;
  budget?: T;
  business?: T;
  message?: T;
  note?: T;
  page?: T;
  locale?: T;
  whatsappOptIn?: T;
  utm?: T;
  eventId?: T;
  crmForwarded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Заголовок и описание страницы для поиска и соцсетей.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Крупный заголовок с 3D-эффектом задан в коде — здесь остальное.
   */
  hero?: {
    /**
     * Широкое фото. Пусто — останется фон из кода.
     */
    bg?: (number | null) | Media;
    /**
     * Вертикальный кроп для экранов до 900px.
     */
    bgMobile?: (number | null) | Media;
    kicker?: string | null;
    /**
     * Главный SEO-заголовок страницы (тег H1). Крупный слоган «From idea to result.» — это визуал, он задан в коде и на индексацию не влияет.
     */
    h1?: string | null;
    desc?: string | null;
    ctaPrimary?: string | null;
    ctaSecondary?: string | null;
  };
  rail?: {
    head?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  problem?: {
    label?: string | null;
    heading?: string | null;
    items?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    onSet?: string | null;
    launch?: string | null;
    all?: string | null;
    /**
     * По порядку: 1-е фото — к 1-му направлению и т.д.
     */
    cardImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Тексты 3 направлений. Фото — в блоке «Фото карточек» выше.
     */
    items?:
      | {
          title: string;
          text?: string | null;
          deliverables?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    steps?:
      | {
          name: string;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  statement?: {
    eyebrow?: string | null;
    line1?: string | null;
    line1Em?: string | null;
    line2?: string | null;
    systems?: string | null;
    cta?: string | null;
  };
  portfolio?: {
    label?: string | null;
    heading?: string | null;
    /**
     * По порядку: 1-е фото — к 1-й карточке и т.д.
     */
    cardImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * 3 карточки-превью на главной. Фото — в блоке выше. Полные кейсы — в разделе «Кейсы».
     */
    cases?:
      | {
          title: string;
          tag?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaStart?: string | null;
    ctaAll?: string | null;
  };
  results?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    /**
     * Само число задано в коде страницы — здесь только подпись.
     */
    items?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  pricing?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    popular?: string | null;
    getStarted?: string | null;
    packages?:
      | {
          name: string;
          tag?: string | null;
          price?: string | null;
          priceOld?: string | null;
          time?: string | null;
          rows?:
            | {
                name: string;
                extra?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    items?:
      | {
          q: string;
          a?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lead?: {
    badge?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    sub?: string | null;
    emailLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showreel".
 */
export interface Showreel {
  id: number;
  label?: string | null;
  heading?: string | null;
  /**
   * Эта часть выводится амбером курсивом.
   */
  headingEm?: string | null;
  lead?: string | null;
  trigger?: string | null;
  book?: string | null;
  play?: string | null;
  close?: string | null;
  orbit?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ровно 3 пункта — иконки заданы в коде по порядку.
   */
  feats?:
    | {
        t: string;
        s: string;
        d?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-index".
 */
export interface ServicesIndex {
  id: number;
  /**
   * Заголовок и описание страницы для поиска и соцсетей.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  label?: string | null;
  h1?: string | null;
  sub?: string | null;
  more?: string | null;
  other?: string | null;
  stats?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    heading?: string | null;
    text?: string | null;
    btn?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page".
 */
export interface PortfolioPage {
  id: number;
  /**
   * Заголовок и описание страницы для поиска и соцсетей.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    sub?: string | null;
  };
  categories?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    ctaBrief?: string | null;
    ctaAbout?: string | null;
  };
  ui?: {
    back?: string | null;
    overview?: string | null;
    next?: string | null;
    clientLabel?: string | null;
    resultLabel?: string | null;
    servicesLabel?: string | null;
    cta?: string | null;
    ctaAll?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-page".
 */
export interface TestimonialsPage {
  id: number;
  /**
   * Заголовок и описание страницы для поиска и соцсетей.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    sub?: string | null;
  };
  featuredLabel?: string | null;
  all?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
  };
  cta?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    ctaBrief?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Заголовок и описание страницы для поиска и соцсетей.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    sub?: string | null;
  };
  story?: {
    label?: string | null;
    heading?: string | null;
    p1?: string | null;
    p2?: string | null;
    slogan?: string | null;
    capabilities?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    items?:
      | {
          title: string;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    /**
     * Само число задано в коде страницы — здесь только подпись.
     */
    items?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    label?: string | null;
    heading?: string | null;
    /**
     * Эта часть выводится амбером курсивом.
     */
    headingEm?: string | null;
    sub?: string | null;
    ctaBrief?: string | null;
    ctaWorks?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  aboutUs?: string | null;
  services?: string | null;
  works?: string | null;
  pricing?: string | null;
  contacts?: string | null;
  callUs?: string | null;
  studio?: string | null;
  language?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-form".
 */
export interface LeadForm {
  id: number;
  name?: string | null;
  phone?: string | null;
  business?: string | null;
  businessPlaceholder?: string | null;
  budget?: string | null;
  budgetPlaceholder?: string | null;
  task?: string | null;
  taskPlaceholder?: string | null;
  whatYouNeed?: string | null;
  services?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  consent?: string | null;
  /**
   * Отдельная галочка (требование Meta). Никогда не должна быть условием отправки заявки.
   */
  whatsappOptIn?: string | null;
  submit?: string | null;
  sending?: string | null;
  success?: string | null;
  errorRequired?: string | null;
  errorSend?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        bg?: T;
        bgMobile?: T;
        kicker?: T;
        h1?: T;
        desc?: T;
        ctaPrimary?: T;
        ctaSecondary?: T;
      };
  rail?:
    | T
    | {
        head?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  problem?:
    | T
    | {
        label?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        onSet?: T;
        launch?: T;
        all?: T;
        cardImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        items?:
          | T
          | {
              title?: T;
              text?: T;
              deliverables?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  process?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        steps?:
          | T
          | {
              name?: T;
              desc?: T;
              id?: T;
            };
      };
  statement?:
    | T
    | {
        eyebrow?: T;
        line1?: T;
        line1Em?: T;
        line2?: T;
        systems?: T;
        cta?: T;
      };
  portfolio?:
    | T
    | {
        label?: T;
        heading?: T;
        cardImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        cases?:
          | T
          | {
              title?: T;
              tag?: T;
              id?: T;
            };
        ctaStart?: T;
        ctaAll?: T;
      };
  results?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        popular?: T;
        getStarted?: T;
        packages?:
          | T
          | {
              name?: T;
              tag?: T;
              price?: T;
              priceOld?: T;
              time?: T;
              rows?:
                | T
                | {
                    name?: T;
                    extra?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faq?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  lead?:
    | T
    | {
        badge?: T;
        heading?: T;
        headingEm?: T;
        sub?: T;
        emailLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showreel_select".
 */
export interface ShowreelSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  headingEm?: T;
  lead?: T;
  trigger?: T;
  book?: T;
  play?: T;
  close?: T;
  orbit?:
    | T
    | {
        text?: T;
        id?: T;
      };
  feats?:
    | T
    | {
        t?: T;
        s?: T;
        d?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-index_select".
 */
export interface ServicesIndexSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  label?: T;
  h1?: T;
  sub?: T;
  more?: T;
  other?: T;
  stats?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        btn?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page_select".
 */
export interface PortfolioPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        sub?: T;
      };
  categories?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        ctaBrief?: T;
        ctaAbout?: T;
      };
  ui?:
    | T
    | {
        back?: T;
        overview?: T;
        next?: T;
        clientLabel?: T;
        resultLabel?: T;
        servicesLabel?: T;
        cta?: T;
        ctaAll?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-page_select".
 */
export interface TestimonialsPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        sub?: T;
      };
  featuredLabel?: T;
  all?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        ctaBrief?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        sub?: T;
      };
  story?:
    | T
    | {
        label?: T;
        heading?: T;
        p1?: T;
        p2?: T;
        slogan?: T;
        capabilities?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        items?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        label?: T;
        heading?: T;
        headingEm?: T;
        sub?: T;
        ctaBrief?: T;
        ctaWorks?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  aboutUs?: T;
  services?: T;
  works?: T;
  pricing?: T;
  contacts?: T;
  callUs?: T;
  studio?: T;
  language?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-form_select".
 */
export interface LeadFormSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  business?: T;
  businessPlaceholder?: T;
  budget?: T;
  budgetPlaceholder?: T;
  task?: T;
  taskPlaceholder?: T;
  whatYouNeed?: T;
  services?:
    | T
    | {
        text?: T;
        id?: T;
      };
  consent?: T;
  whatsappOptIn?: T;
  submit?: T;
  sending?: T;
  success?: T;
  errorRequired?: T;
  errorSend?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}